### ISSUE TITLE
Disconnected, reason = 0x3E

### ISSUE THREAD

**Issue by IHateNameStealers** [neilsheps/xiaoxiang-jbd-bms-ble-reader#1]
Hi Neil,

Trying your code, and it does discover my BMS.
When I try to connect to it I keep getting a "Disconnected, reason = 0x3E".
Anyway to fix this?

I know. The code is old, but so it the BMS I'm using :-)

Noel

**Comment by neilsheps** [comment]
That’s a new one to me that I don’t recall seeing before.  My code is embedded in something right now (working fine) where I don’t have access to a debug link. I do know that sometimes the devices would disconnect immediately after connection because the nrf52 couldn’t discover the required service or characteristic. I made the code disconnect completely, go back to scanning, and repeat the connection attempt. I estimate that connections were 70-80% successful, so it almost never took more than 1-2 attempts before a successful connection. However, in that case it was my code driving the disconnection. The only other thing I can think of is that your BMS is PIN protected. I left my pin at 0000 or whatever. I suspect that if it’s set to something other than 0000 it might require pairing before connection. Hope this gives you something to work with. On Jun 7, 2024, at 11:54 PM, IHateNameStealers ***@***.***> wrote:﻿
Hi Neil,
Trying your code, and it does discover my BMS.
When I try to connect to it I keep getting a "Disconnected, reason = 0x3E".
Anyway to fix this?
I know. The code is old, but so it the BMS I'm using :-)
Noel

**Comment by IHateNameStealers** [comment]
Thank you for getting back to me.

I have moved the setup a bit closer together, and guess what. All is working fine now :-)

Thank you.
